URL_BANCO_VETORES = 'banco_vetores_alrn_adicional'
URL_LLAMA='http://localhost:11434'
THREADPOOL_MAX_WORKERS=10
EMBEDDING_INSTRUCTOR="hkunlp/instructor-xl"
DEVICE='cpu'
#DEVICE='cuda'
TIPO_DE_BUSCA='mmr'
# TIPO_DE_BUSCA='similarity'
# TIPO_DE_BUSCA='similarity_score_threshold'
NUM_DOCUMENTOS_RETORNADOS=5
LIMIAR_SCORE_SIMILARIDADE=0.6


MODELO_DE_EMBEDDINGS = EMBEDDING_INSTRUCTOR